# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xPtJDL_XBc_VmRttW7njcDNzb01PB34
"""

import streamlit as st
import pandas as pd
import os
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent

# Configuración de la página
st.set_page_config(page_title="Agente Hidrológico CDMX", layout="wide")
st.title("🌊 Análisis de Hidrología CDMX")

# 1. Configuración de API Key (vía Secrets o Sidebar)
api_key = st.sidebar.text_input("Introduce tu Google API Key", type="password")

if api_key:
    os.environ["GOOGLE_API_KEY"] = api_key

    # 2. Carga de datos

    @st.cache_data
    def load_data():
        file_id = '1bq9eLLaT5a386AhtGEKz2QuxzGzGwuAD'
        url = f'https://drive.google.com/uc?id={file_id}'
        return pd.read_csv(url)

    df = load_data()
    st.write("### Vista previa de los datos", df.head(5))

    # 3. Inicialización del Agente
    llm = ChatGoogleGenerativeAI(
        model="gemini-2.5-pro",
        temperature=0,
        max_output_tokens=None,
        timeout=None,
        max_retries=2,)
    custom_prefix = """
Eres un Agente de Análisis de Datos de Hidrología.
TU REGLA DE ORO: No saludes ni des introducciones. Responde únicamente en el formato esperado por la herramienta.
Tu objetivo es analizar datos, generar visualizaciones y redactar reportes.

Siempre que necesites ejecutar código, tu respuesta debe seguir el formato:
Thought: (Tu razonamiento sobre lo que necesitas hacer para responder la pregunta, los pasos que vas a seguir y las columnas o filtros que usarás. Este pensamiento no es para el usuario. Es para el agente interno.)
Action: python_repl_ast
Action Input: (Tu código Python para ejecutar)

CAPACIDADES:
1. Puedes usar matplotlib para generar gráficos. Siempre usa 'plt.show()' al final de un gráfico.
2. Puedes realizar comparativas temporales si los datos tienen columnas de fecha o año.
3. Para reportes, sé profesional y estructurado.


Datos disponibles (además de los básicos):
- Municipio: Nombre de la zona.
Si has determinado la respuesta final a la pregunta, tu respuesta debe seguir el formato:
Thought: (Tu razonamiento sobre cómo llegaste a la respuesta final)
Final Answer: (La respuesta final a la pregunta)

Datos disponibles:
- volumen_actual_litros: Cantidad actual en el tanque.
- litros_consumidos_raw: Gasto detectado.
- indicador_posible_fuga: 'SI' o 'NO'.
- tipo_suministro_v2: 'Pipa' o 'Red'.
      id_sensor_tuya,
      nombre_ubicacion,
      estado,
      municipio,
      cp_sensor,
      localizacion,
      ID_EDO,
      ID_MUN,
      REGION,
      granularidad,
      fecha_lectura_time, # Usar el timeframe más granular (time)
      es_rotoplas,
      capacidad_litros,
      poblacion_size,
      esta_disponible,
      esta_online,
      notificacion_nivel_agua,
      profundidad_liquida_mm,
      porcentaje_nivel_liquido,
      profundidad_maxima_mm,
      estado_liquido_alarma,
      set_max_n,
      set_mini_n,
      promedio_nivel_nacional,
      conteo_alarma_activa
"""
    agent = create_pandas_dataframe_agent(
        llm=llm,
        df=df,
        verbose=True,
        prefix=custom_prefix,
        allow_dangerous_code=True,
        handle_parsing_errors=True
    )


    # 4. Interfaz de Chat
    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("¿Qué quieres saber sobre el consumo hídrico?"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            # Aquí el agente procesa y responde
            response = agent.run(prompt)
            st.markdown(response)
            st.session_state.messages.append({"role": "assistant", "content": response})
else:
    st.warning("Por favor, ingresa tu API Key en la barra lateral para comenzar.")
